### PR TITLE
Static views

### LINKED ISSUE #1: Static views
* Login page
* Registration page
* Document list
* Document

### PR DESCRIPTION
**Pull request by actisPRO**
Finished basic UI for MVP, almost without any JS.
We may also want to add more modules to editorjs.

Closes #1

### CODE REVIEW

**Comment by AlbertCerfeda** [comment]
I'll take a look at it ;)

**Comment by Alessandro-Gobbetti** [comment]
Ok, nice!
I like it. Just two little things:

1. we should ask for an email in the registration form;
2. we cannot use editor.js since it doesn't allow collaborative editing (there are other editors for this), but it's fine for now

Good job!

**Review by Alessandro-Gobbetti — APPROVED** [review]
Ok, nice!
I like it. Just two little things:

1. we should ask for an email in the registration form;
2. we cannot use editor.js since it doesn't allow collaborative editing (there are other editors for this), but it's fine for now.

Good job!

**Comment by actisPRO** [comment]
> Ok, nice! I like it. Just two little things:
> 
> 1. we should ask for an email in the registration form;
> 2. we cannot use editor.js since it doesn't allow collaborative editing (there are other editors for this), but it's fine for now.
> 
> Good job!

We'll implement email later, not for MVP.
As for editor js, we can implement collaboration module by ourselves (or ofc use another solution)

**Pull request merged**
